# Generated by Django 3.2.7 on 2021-10-06 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='number',
            new_name='phone',
        ),
    ]
